import test from 'node:test';
import assert from 'node:assert/strict';
import {Narrator,LocalRecorder} from '../src/audio.mjs';
const settings={narration:true,locale:'en-CA',slow:false};
function mockGlobal(t,name,value){const old=Object.getOwnPropertyDescriptor(globalThis,name);Object.defineProperty(globalThis,name,{value,configurable:true,writable:true});t.after(()=>old?Object.defineProperty(globalThis,name,old):delete globalThis[name]);}
function voiceHarness(t,voices=[{localService:true,lang:'en-CA'}]){const spoken=[];mockGlobal(t,'SpeechSynthesisUtterance',class{constructor(text){this.text=text;}});mockGlobal(t,'speechSynthesis',{getVoices:()=>voices,speak:u=>spoken.push(u),cancel(){},pause(){},resume(){}});return spoken;}
test('narration refuses remote-only voices and leaves play available',async t=>{const spoken=voiceHarness(t,[{localService:false,lang:'en-US'}]);const statuses=[];const n=new Narrator(s=>statuses.push(s));assert.equal(await n.speak(['Hello'],settings),false);assert.equal(spoken.length,0);assert.match(statuses.at(-1),/No local English voice/);});
test('stopping during voice discovery prevents late speech',async t=>{const voices=[];const spoken=voiceHarness(t,voices);const n=new Narrator();const result=n.speak(['Hello'],settings);n.stop();voices.push({localService:true,lang:'en-US'});assert.equal(await result,false);assert.equal(spoken.length,0);});
test('late end of cancelled speech cannot detach newer pending narration',async t=>{const spoken=voiceHarness(t);const n=new Narrator();const first=n.speak(['Old'],settings);const second=n.speak(['New'],settings);spoken[0].onend();assert.equal(await first,false);assert.equal(typeof n.pending,'function');n.stop();assert.equal(await second,false);});
test('sentences advance only when the current utterance actually ends',async t=>{const spoken=voiceHarness(t),indices=[];const n=new Narrator();const result=n.speak(['One.','Two.'],settings,i=>indices.push(i));assert.deepEqual(indices,[0]);spoken[0].onend();await Promise.resolve();assert.deepEqual(indices,[0,1]);spoken[1].onend();assert.equal(await result,true);});
test('disabled recording does not request microphone permission',async t=>{let requests=0;mockGlobal(t,'navigator',{mediaDevices:{getUserMedia:async()=>{requests++;}}});const r=new LocalRecorder();await r.start(false);assert.equal(requests,0);});
test('late microphone grant after navigation immediately stops its tracks',async t=>{let grant,stops=0;mockGlobal(t,'navigator',{mediaDevices:{getUserMedia:()=>new Promise(resolve=>grant=resolve)}});mockGlobal(t,'MediaRecorder',class{constructor(){throw Error('Must not start after navigation');}});const r=new LocalRecorder();const pending=r.start(true);r.clear();grant({getTracks:()=>[{stop:()=>stops++}]});await pending;assert.equal(stops,1);assert.equal(r.recorder,null);});
test('recorder construction failure releases the acquired stream',async t=>{let stops=0;mockGlobal(t,'navigator',{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop:()=>stops++}]})}});mockGlobal(t,'MediaRecorder',class{constructor(){throw Error('Unsupported format');}});const statuses=[];const r=new LocalRecorder(s=>statuses.push(s));await r.start(true);assert.equal(stops,1);assert.equal(r.stream,null);assert.match(statuses.at(-1),/still practice and finish/);});
test('permission denial gives a non-blocking message',async t=>{mockGlobal(t,'navigator',{mediaDevices:{getUserMedia:async()=>{throw Error('NotAllowedError');}}});mockGlobal(t,'MediaRecorder',class{});const statuses=[];const r=new LocalRecorder(s=>statuses.push(s));await r.start(true);assert.match(statuses.at(-1),/still practice and finish/);assert.equal(r.stream,null);});
