import test from 'node:test';
import assert from 'node:assert/strict';
import {Narrator,LocalRecorder} from '../src/audio.mjs';
const settings={narration:true,locale:'en-CA',slow:false};
function mockGlobal(t,name,value){const old=Object.getOwnPropertyDescriptor(globalThis,name);Object.defineProperty(globalThis,name,{value,configurable:true,writable:true});t.after(()=>old?Object.defineProperty(globalThis,name,old):delete globalThis[name]);}
test('missing recordings never fall back to a robotic browser voice',async t=>{let spoken=0;mockGlobal(t,'SpeechSynthesisUtterance',class{});mockGlobal(t,'speechSynthesis',{speak:()=>spoken++,cancel(){},pause(){},resume(){}});const statuses=[];const n=new Narrator(s=>statuses.push(s));assert.equal(await n.speak(['Missing'],settings),false);assert.equal(spoken,0);assert.match(statuses.at(-1),/recording is not available/);});
test('disabled recording does not request microphone permission',async t=>{let requests=0;mockGlobal(t,'navigator',{mediaDevices:{getUserMedia:async()=>{requests++;}}});const r=new LocalRecorder();await r.start(false);assert.equal(requests,0);});
test('late microphone grant after navigation immediately stops its tracks',async t=>{let grant,stops=0;mockGlobal(t,'navigator',{mediaDevices:{getUserMedia:()=>new Promise(resolve=>grant=resolve)}});mockGlobal(t,'MediaRecorder',class{constructor(){throw Error('Must not start after navigation');}});const r=new LocalRecorder();const pending=r.start(true);r.clear();grant({getTracks:()=>[{stop:()=>stops++}]});await pending;assert.equal(stops,1);assert.equal(r.recorder,null);});
test('recorder construction failure releases the acquired stream',async t=>{let stops=0;mockGlobal(t,'navigator',{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop:()=>stops++}]})}});mockGlobal(t,'MediaRecorder',class{constructor(){throw Error('Unsupported format');}});const statuses=[];const r=new LocalRecorder(s=>statuses.push(s));await r.start(true);assert.equal(stops,1);assert.equal(r.stream,null);assert.match(statuses.at(-1),/still practice and finish/);});
test('permission denial gives a non-blocking message',async t=>{mockGlobal(t,'navigator',{mediaDevices:{getUserMedia:async()=>{throw Error('NotAllowedError');}}});mockGlobal(t,'MediaRecorder',class{});const statuses=[];const r=new LocalRecorder(s=>statuses.push(s));await r.start(true);assert.match(statuses.at(-1),/still practice and finish/);assert.equal(r.stream,null);});
