// Original authored page triples: Sprout sentence | Trail addition | Ranger addition.
// Versions are cumulative support edits, not different stories. Human editorial/audio sign-off pending.
export const scripts = [
['The Envelope With No Name', 'hello friend name smile help give', [
['Pip has a letter.','The letter has no name.','A leaf-shaped seal shows that it belongs to the Explorer Club.'],
['Pip sees a friend.','He says hello to Nori.','Nori stops painting to listen to the invitation.'],
['Nori has a name card.','The card is blue.','She places it beside the letter, but the two shapes do not match.'],
['A child waves to Pip.','The child has a leaf card.','The leaf fits the empty space on the envelope.'],
['Pip gives the letter to the child.','The letter says welcome.','The new explorer is invited to help make the Wonderwood Atlas.'],
['The friends smile.','They walk to the club together.','An empty page is waiting for their first discovery.']]],
['A Seat for Every Friend','friend family chair little more together',[
['Nori sets out a chair.','Her family is coming to the club.','She puts the chairs in a circle so everyone can see one another.'],
['Her brother brings a blanket.','He puts it beside the chairs.','The blanket makes a comfortable place for anyone who prefers the floor.'],
['A baby comes with an adult.','The baby sits with the adult.','Nori leaves space for their bag beside the seat.'],
['Pip has no chair.','One more friend needs a place.','Nobody wants Pip to stand outside the circle.'],
['Nori moves her chair.','The friends make more room.','Her brother brings another chair from the reading corner.'],
['Every friend has a seat.','They tell a story together.','The circle is wider now, and every voice belongs in it.']]],
['The Silly Shadow','head hand arm leg foot body',[
['Pip sees a shadow.','It is beside his foot.','The low afternoon sun makes his shadow stretch across the meadow.'],
['Pip lifts his hand.','The shadow lifts a hand too.','He notices that the dark shape moves when his body moves.'],
['Pip bends one knee.','His shadow looks funny.','Nori draws a chalk line around the bent leg.'],
['A cloud hides the sun.','The shadow is hard to see.','Pip waits instead of trying to catch it.'],
['The sun comes out.','Pip stretches both arms.','The shadow returns beside Nori’s chalk drawing.'],
['Pip makes a new pose.','Nori draws the shadow.','They label the head, arms, and legs on their moving-body page.']]],
['Where Is My Footprint?','foot toe hand finger small look',[
['Nori sees a mark.','The mark is in soft sand.','She wants to know which explorer made it.'],
['Pip shows his hand.','His fingers make a new mark.','The handprint is wide, with five finger shapes spreading out.'],
['Nori looks at her foot.','She wiggles her toes.','She takes off one shoe while sitting safely on the blanket.'],
['Nori presses her foot in the sand.','It makes a small footprint.','She keeps the new print beside the old mark for comparison.'],
['The two marks match.','The old mark is Nori’s footprint.','Both have the same curved edge and little toe marks.'],
['Nori puts on her shoe.','Pip draws the two prints.','Their journal shows how looking closely helped solve the mystery.']]],
['The Rainbow’s Missing Stripe','red blue yellow green purple color',[
['Bea paints a rainbow.','She has red and yellow paint.','The club mural needs one more stripe before the parade.'],
['Pip brings blue paint.','He puts it by the yellow paint.','Both jars are closed so nothing spills on the path.'],
['Bea needs green.','The green jar is empty.','She looks at the colors she already has.'],
['Bea mixes blue and yellow.','The paint turns green.','She tests a little paint on spare paper before using it on the mural.'],
['Bea paints the green stripe.','Pip adds a purple flower.','They leave the picture to dry instead of touching the wet paint.'],
['The rainbow is ready.','Everyone finds a favorite color.','Bea writes down how she made green so the club can mix it again.']]],
['A House Made of Shapes','square triangle circle rectangle door roof',[
['Nori draws a square.','It will be a little house.','She draws it in the middle of a large sheet of paper.'],
['Pip brings a triangle.','The triangle is the roof.','Its three straight sides make a point above the square.'],
['Bea adds a rectangle.','It is a tall door.','She leaves enough space beside it for a window.'],
['The window is missing.','Nori finds a blue circle.','The round piece fits in the space beside the door.'],
['Pip adds a star.','The star goes above the house.','He chooses the sky instead of covering the window.'],
['The shape house is finished.','The friends point to each shape.','Their picture uses a square, a triangle, a rectangle, a circle, and a star.']]],
['Twenty Tickets for the Train','one two ten twenty seat train',[
['Pip has ten tickets.','They are in a red box.','He lays them in a row so he can check the number.'],
['Nori brings ten more.','Her tickets are in a blue box.','She places a second row below Pip’s first row.'],
['The friends count twenty tickets.','Ten and ten make twenty.','They touch each ticket once to avoid counting it twice.'],
['One ticket falls.','It lands under a seat.','Bea sees a red corner peeking out near the chair leg.'],
['Bea gets the ticket.','Pip counts the tickets again.','There are still twenty, so none are missing from the two rows.'],
['The little train is ready.','Each rider gets one ticket.','Pip keeps the boxes for another counting game at the carnival.']]],
['The Lantern Count','one three four five six night',[
['Nori hangs three lanterns.','They glow over the path.','An adult has checked that the little lights are safe to use.'],
['Pip brings two lanterns.','Three and two make five.','They put each lantern beside a painted number on the railing.'],
['Bea finds one more.','Now there are six lanterns.','She carries it carefully to the last empty hook.'],
['One lantern is dark.','It is lantern number four.','The lantern is there, but its switch is off.'],
['An adult turns on the light.','All six lanterns glow.','Nori counts the lanterns, not just the lights that were on.'],
['The path is bright.','The friends walk home together.','Their journal shows six lanterns in order from one to six.']]],
['A Bed Beneath the Stars','bed pillow blanket window night home',[
['Pip brings a bed.','It goes in the treehouse.','Bea helps place it on the flat floor away from the doorway.'],
['Nori brings a pillow.','The pillow is soft.','She adds it at the head of the bed for a comfortable reading rest.'],
['Bea finds a blanket.','She folds it on the bed.','The blanket is ready for a cool evening.'],
['Pip wants to see the stars.','A curtain covers the window.','He can stay indoors and still look at the night sky.'],
['Nori opens the curtain.','The stars shine outside.','The window remains closed while the friends get cozy.'],
['Pip reads in bed.','His friends sit nearby.','The treehouse has become a warm home for their evening story.']]],
['The Key in the Quiet Room','key room shelf book lamp under',[
['Bea has a key.','It opens the book cupboard.','She brings it to the quiet room before the reading club arrives.'],
['Bea puts down a book.','The book is beside the lamp.','Then she arranges the cushions for her friends.'],
['The key is missing.','Bea looks on the shelf.','Only a small bowl and two storybooks are there.'],
['Pip looks under the book.','The key is there.','A corner of the key was hidden beneath the book’s cover.'],
['Bea opens the cupboard.','She takes out a story.','Pip puts the key in the little bowl where everyone can find it.'],
['The room is quiet.','The friends listen to Bea.','Their new rule is simple: the key goes in the bowl after reading.']]],
['The Rolling Apple','apple pear basket carrot roll stop',[
['Nori packs an apple.','She puts it in a basket.','The picnic list also asks for a pear and a carrot.'],
['Pip brings a pear.','Nori adds a carrot.','They check the list before carrying the basket to the orchard.'],
['The apple rolls out.','It rolls down the path.','The basket tipped when Pip set it on a sloping stone.'],
['Bea stops the apple.','It lands by her shoe.','She picks it up and shows Nori where it went.'],
['An adult washes the apple.','Nori closes the basket.','They put the basket on flat ground this time.'],
['The friends share the picnic.','The apple is back.','Nori draws a basket with a lid for the club’s packing guide.']]],
['A Picnic for Everyone','bread rice milk cheese food please',[
['Pip brings bread.','Nori brings rice.','They ask each friend what they would like before serving the picnic.'],
['Bea brings cheese.','An adult checks the food.','The adult asks about allergies and keeps foods separate where needed.'],
['Nori wants water.','She does not want milk.','Pip listens instead of choosing a drink for her.'],
['Pip gives Nori water.','Nori says please and thank you.','Bea places a clean cup beside Nori’s plate.'],
['Each friend chooses food.','Nobody has to try everything.','There is room on the blanket for different lunches and different tastes.'],
['The picnic feels kind.','The friends clean up together.','Their picnic page says that asking and listening help everyone feel welcome.']]],
['A Soft Bed for Pip','cat kitten soft bowl gentle sleep',[
['Pip visits a kitten.','An adult stays with him.','The kitten is a pet at the care club, not a wild animal.'],
['The kitten has fur.','Its fur looks soft.','Pip waits for the adult to explain how to approach it gently.'],
['The kitten needs a bed.','Pip finds a blanket.','He folds it into a quiet corner away from busy feet.'],
['The adult sets down a bowl.','The bowl has fresh water.','Pip watches rather than giving the kitten food without asking.'],
['The kitten lies on the blanket.','Pip uses a quiet voice.','He gives the kitten space to choose whether to come closer.'],
['The kitten goes to sleep.','Pip lets it rest.','His care-club note says that a sleeping pet needs a peaceful place.']]],
['The Puppy Who Needed a Rest','puppy dog tired rest drink gentle',[
['A puppy has a ball.','It plays with an adult.','The care club watches the game from a little distance.'],
['The puppy has a nose.','It sniffs the grass.','Its nose moves close to the ground as it explores the garden.'],
['The puppy stops playing.','It lies down in the shade.','Pip notices that the puppy is no longer bringing the ball back.'],
['Pip puts the ball away.','The puppy can rest.','The adult says that they should not pull the puppy back into the game.'],
['The adult brings water.','The puppy takes a drink.','Nori keeps the quiet resting corner clear.'],
['The club draws the puppy.','They use gentle voices.','Their picture shows that caring can mean stopping a game and giving space.']]],
['Bea and the Floating Stick','beaver tail flat swim stick dam',[
['Look! A beaver. This is Bea.','She is beside the creek.','The explorers watch quietly from the bank.'],
['Bea has brown fur and a flat tail.','Her tail is wide.','They sketch these features to help recognize her again.'],
['A stick is in the water.','The stick floats away.','Bea enters the creek while the explorers stay back.'],
['Bea can swim. She gets the stick.','She brings it back through the water.','Her webbed back feet help her move through the creek.'],
['Bea takes the stick to a dam.','A dam can slow the water.','A lodge is a home, while a dam holds back flowing water.'],
['The stick is on the dam.','The explorers draw Bea’s tail.','They add a separate dam drawing so their Atlas does not confuse it with her home.']]],
['A Door Under the Water','lodge dam home water mud bank',[
['Bea swims in the pond.','She is near her lodge.','Pip observes her from the bank with a grown-up.'],
['The lodge is Bea’s home.','It is made with sticks and mud.','Its thick walls shelter a living space inside.'],
['Bea goes under the water.','Her entrance is below the surface.','The underwater entrance leads into the lodge.'],
['The home has a dry room.','The room is above the water.','The explorers use a guidebook picture to see the room without disturbing Bea.'],
['Pip draws a dam too.','The dam slows the stream.','He labels the two structures separately because they do different jobs.'],
['Bea rests in her home.','Pip leaves the lodge alone.','The best discovery today is a drawing, not a visit inside an animal’s home.']]],
['The Missing Nut Map','squirrel nut tree seed branch tail',[
['A squirrel has a nut.','It sits beside a tree.','The explorers see the squirrel from their woodland path.'],
['Its tail is bushy.','It holds the nut in its front paws.','Nori draws the tail instead of moving closer to touch it.'],
['The squirrel runs to the soil.','It buries the nut.','Some squirrels hide food to find and eat later.'],
['Nori drops her map.','It lands beside a root.','A breeze folds the paper under a dry leaf.'],
['Pip finds the map.','He leaves the buried nut alone.','The nut belongs in the animal’s food store, not in the club’s collection.'],
['The explorers draw the tree.','They mark where they stood.','Their map records the observation without marking a place to dig.']]],
['Who Passed the Reading Tree?','owl fox paw track tree night',[
['Pip finds a track.','It is under the reading tree.','He looks at the ground without walking over the mark.'],
['An owl sits above him.','The owl has feathers.','Its feet grip the branch while it rests.'],
['The track looks like a paw.','It is not a feather.','Nori draws the print before looking for more clues.'],
['A fox walks along the path.','Its paws leave new tracks.','The new marks resemble the one beside the reading tree.'],
['Pip compares the tracks.','A fox may have passed here.','He says may because he did not see who made the first print.'],
['The owl stays on the branch.','The friends leave quietly.','Their journal separates what they saw from what they think happened.']]],
['The Smallest Garden Guest','snail shell small leaf garden slow',[
['Nori sees a snail.','It is on a green leaf.','She bends near the garden bed without pulling the leaf away.'],
['The snail has a shell.','Its soft body is below the shell.','The shell is part of its body, not a borrowed house to remove.'],
['The snail moves slowly.','A silvery trail is behind it.','Pip follows the trail with his eyes instead of touching the snail.'],
['A watering can tips.','An adult stands it up.','The friends keep the heavy can away from the little garden guest.'],
['Nori draws the shell.','Pip draws the trail.','Their two drawings show appearance and movement separately.'],
['The snail reaches another leaf.','The explorers give it space.','Their garden page celebrates an animal that was easy to miss.']]],
['Six Legs at the Flower Gate','insect bee six spider eight wing',[
['A bee visits a flower.','It has six legs.','The explorers count the legs in a close-up guidebook picture.'],
['The bee has wings.','It moves between flowers.','Bees collect food from flowers and can carry pollen between them.'],
['A spider sits nearby.','It has eight legs.','The guidebook calls the spider an arachnid, not an insect.'],
['Pip has two picture cards.','One card shows six legs.','He wants to put the insect card on the correct journal page.'],
['Pip chooses the bee card.','The spider has its own page.','Having a small body does not make every tiny animal an insect.'],
['The flower gate stays quiet.','The explorers watch from a distance.','They do not touch the bee or damage the spider’s web.']]],
['The Long-Neck Lookout','giraffe long neck tall leaf spot',[
['The Atlas shows a giraffe.','It stands on an African grassland.','The club is visiting a place in a book rather than moving wild animals into Wonderwood.'],
['The giraffe has a long neck.','Its coat has patches.','Nori sketches both features before writing its name.'],
['The giraffe reaches leaves.','The leaves are high in a tree.','Its height helps it reach food that is above the explorers’ heads.'],
['Pip drops a leaf card.','It falls beside a short bush.','The card is a drawing, not food to offer the animal.'],
['Nori finds the card.','She puts it on the giraffe page.','She connects the high leaves in the picture with the giraffe’s long neck.'],
['The passport gets a stamp.','The club closes the book.','Their observation page describes a giraffe’s appearance and what it was eating.']]],
['A Stripe for the Field Guide','zebra stripe black white animal grass',[
['The Atlas shows a zebra.','It is eating grass.','This page takes the club to an African grassland habitat.'],
['The zebra has stripes.','The stripes are black and white.','Different zebras have different stripe patterns.'],
['Pip finds a spotted card.','It is on the wrong page.','The card belongs with the giraffe picture they studied earlier.'],
['Nori finds a striped card.','It matches the zebra.','She compares the whole pattern instead of choosing by color alone.'],
['The cards go on separate pages.','The zebra keeps eating grass.','The club records the food visible in the picture without guessing what every animal eats.'],
['The field guide is ready.','Pip points to the stripes.','A stripe is a long band, while a spot is a separate patch or mark.']]],
['The Postcard With Flippers','seal flipper ocean beach swim rest',[
['A postcard shows a seal.','The seal rests on a beach.','The picture is an observation of a harbor seal beside the ocean.'],
['The seal has flippers.','It does not have walking hands.','Its limbs are shaped for movement in water.'],
['The seal enters the ocean.','It swims away from the sand.','The club follows the action across the postcard pictures.'],
['Pip has a fish card.','The card does not show flippers.','He checks the body parts instead of assuming everything that swims is a fish.'],
['Nori finds the seal card.','She places it beside the postcard.','Seals are mammals, even though they spend much of their time in water.'],
['The club draws the flippers.','They leave real seals alone.','A beach animal needs space, so watching from far away is the safe choice.']]],
['A Shell Beside the Tide','crab shell beach sand tide wave',[
['Nori sees a crab.','It is beside a tide pool.','She watches with an adult from a stable place away from the waves.'],
['The crab has a hard shell.','Its claws are in front.','Its outer covering protects its body.'],
['A wave reaches the sand.','The water moves closer.','The adult says the tide can change the space available on the beach.'],
['The club moves back.','They stay on the safe path.','They leave the crab and its tide pool undisturbed.'],
['Pip draws a shell.','Nori draws the wave.','Their picture records the visit without taking an animal home.'],
['The postcard is finished.','The crab stays by the pool.','The explorers remember that a changing shore is an animal’s habitat.']]],
['A Morning in the Barn','hen chick cow hay barn egg',[
['The farmer opens the barn.','The club visits with an adult.','Pip waits at the gate for the farmer to invite them in.'],
['A hen has feathers.','Her chick follows her.','A chick is a young chicken with soft down before its adult feathers grow.'],
['A cow eats hay.','The farmer puts hay in a feeder.','The club watches without reaching through the fence.'],
['Pip finds an egg picture.','The picture belongs on the hen page.','He is sorting cards, not collecting real eggs on his own.'],
['Nori draws the chick.','She uses a yellow crayon.','The color describes this chick; not every chick has the same coloring.'],
['The barn visit ends.','The friends wash their hands.','Their farm page shows feathers, hay, and the animals they observed.']]],
['The Woolly Weather Report','sheep wool coat warm farm rain',[
['A sheep stands in a field.','Its body has wool.','The farmer calls the woolly coat a fleece.'],
['The sky turns cloudy.','Pip feels a cool wind.','The club checks the weather before continuing the farm walk.'],
['Nori brings her coat.','Her coat feels warm.','She does not need to touch the sheep to compare two kinds of covering.'],
['Rain begins to fall.','The farmer leads the way inside.','The animals have suitable shelter, and the visitors follow the farm’s instructions.'],
['Pip draws the sheep’s wool.','Nori draws her coat.','They label the sheep’s natural covering separately from the clothing people make.'],
['The report says rainy.','The club stays dry.','Their weather page explains why the outdoor plan changed.']]],
['The Mitten on the Train','mitten glove scarf pocket hat train',[
['Pip finds a mitten.','It is on a train seat.','He tells the adult traveling with the club.'],
['Nori has a glove.','Her glove has finger spaces.','The mitten has one thumb space and one larger space for the other fingers.'],
['Bea checks her pocket.','Her scarf is there.','She does not take the mitten because it is not hers.'],
['A child looks worried.','The child has one mitten.','Its green pattern matches the mitten on the seat.'],
['The adult helps return it.','The child has two mittens now.','Pip lets the adult check that the item goes to its owner.'],
['The train reaches the station.','The child waves goodbye.','Nori draws a mitten and a glove on their clothing page.']]],
['A Coat for the Cloudy Day','coat shirt boot umbrella wet dry',[
['Nori packs a shirt.','She wants to play outside.','She looks through the window before closing her bag.'],
['The sky is cloudy.','Rain taps on the roof.','A weather picture confirms that the afternoon will be wet.'],
['Nori adds a coat.','Pip brings his boots.','They choose clothing that fits the day’s weather.'],
['Bea brings an umbrella.','An adult checks the path.','They will stay indoors if the weather becomes unsafe.'],
['The friends take a short walk.','Their feet stay dry.','They return before the rain gets heavier.'],
['Nori hangs up her coat.','Pip puts his boots by the door.','The clothing page shows how looking outside helped them choose.']]],
['The Cloud That Changed the Plan','cloud wind sun rain inside outside',[
['Pip plans an outdoor game.','The sun is warm.','He puts a paper map on the picnic table.'],
['A cloud covers the sun.','The wind blows the map.','Bea holds one corner so it does not fly into the creek.'],
['Rain begins to fall.','The paper gets wet.','The adult asks the club to bring the game indoors.'],
['Nori carries the map inside.','Bea dries the table.','Pip moves the picture cards to the treehouse floor.'],
['The friends play indoors.','The game still works.','Changing the location does not mean giving up their adventure.'],
['Pip draws a rain cloud.','He writes a new plan.','His page has an outdoor choice and an indoor choice for next time.']]],
['Rain on Parade Day','rain rainbow sky wet dry parade',[
['The parade banner is ready.','It hangs outside the club.','Nori painted it on paper with her friends.'],
['Rain falls on the path.','Pip sees the wet banner.','He asks an adult to help take it down safely.'],
['The friends move inside.','They lay the banner flat.','They wait for the paper to dry before repairing the colors.'],
['Bea paints a new rainbow.','Nori fixes a blue stripe.','Pip brings dry paper for a small welcome sign.'],
['The rain stops.','The adult checks outside.','The club can continue only after the path is safe to use.'],
['The parade begins.','The banner is bright again.','Their weather page says that a delay can become time to help.']]],
['The Backpack Mix-Up','backpack book pencil crayon name school',[
['Pip brings a backpack.','It is blue.','The first school adventure starts in the treehouse classroom.'],
['Nori has a blue backpack too.','The bags look alike.','She puts hers beside Pip’s bag near the door.'],
['Pip opens the wrong bag.','He finds Nori’s crayons.','His own bag should have a book and a pencil.'],
['Nori checks the name cards.','Her name is on one bag.','The cards help even when the colors are the same.'],
['The friends swap bags.','Pip finds his book.','They put the name cards where they are easier to see.'],
['The class is ready.','Nori shares a crayon.','Their classroom rule is to check a name before taking a bag.']]],
['A Book for the New Student','student teacher book page story help',[
['A new student comes in.','The teacher says hello.','Nori makes space at the reading table.'],
['The student sees a book.','The cover shows a beaver.','The student points to the animal before trying to read its name.'],
['A word looks difficult.','The student asks for help.','Pip offers to listen to the page together.'],
['The teacher reads the page.','The student points to the tail.','The picture helps connect the spoken word to the story.'],
['The student turns a page.','Nori waits patiently.','Nobody needs to read quickly to belong in the reading group.'],
['The friends finish the story.','The student chooses another book.','Their welcome page says that asking for help is part of learning.']]],
['The Ball Beyond the Bridge','ball roll bridge stop adult help',[
['Pip rolls a ball.','It goes toward a bridge.','The club is playing in the marked play area.'],
['The ball rolls too far.','It stops beyond the bridge.','The path ahead is outside the place the adult checked.'],
['Pip stops at the line.','He does not chase the ball.','He remembers that getting a toy back is less important than staying safe.'],
['Pip asks an adult for help.','Nori waits with him.','The adult checks the route before retrieving the ball.'],
['The adult brings it back.','The friends move the game.','They choose a flat area farther from the bridge.'],
['Pip rolls gently.','Nori catches the ball.','Their motion page includes stopping and asking for help.']]],
['A Path of Hops and Steps','hop walk jump turn stop start',[
['Bea draws a path.','It has circles and squares.','The marks make a pretend adventure course on a safe flat floor.'],
['Pip hops to a circle.','Nori walks to a square.','Each explorer chooses a comfortable way to move.'],
['A card says turn.','Bea turns at the arrow.','She looks ahead before moving to the next shape.'],
['Pip wants a break.','The friends stop together.','They can finish the course later without losing their place.'],
['Nori starts again.','She takes two small steps.','A seated explorer can move a token along the same course.'],
['Everyone reaches the end.','They wave to one another.','Their adventure works with different bodies and different movements.']]],
['A Quiet Place for Nori','quiet loud shy calm friend listen',[
['The festival is loud.','Nori covers her ears.','Drums and excited voices fill the little square.'],
['Pip asks Nori a question.','Nori wants a quiet place.','Pip listens to her words instead of guessing what she needs.'],
['They find a reading corner.','It is away from the drums.','An adult can still see them from the festival table.'],
['Nori sits with a book.','Pip sits nearby.','He does not make her talk while she is resting.'],
['Nori feels calm.','She chooses to watch the parade.','She can return to the quiet corner whenever she needs a break.'],
['Pip makes a quiet sign.','The corner is for everyone.','Their friendship page says that fun can be quiet as well as loud.']]],
['The Game With One More Player','share turn wait kind lonely together',[
['Pip and Bea play a game.','Nori watches beside them.','There are two tokens on the board.'],
['Nori wants to join.','She feels lonely outside the game.','Pip notices her standing near the empty chair.'],
['Pip asks Nori to play.','Bea finds another token.','They choose a smooth leaf marker for the new player.'],
['The friends take turns.','Nori waits while Bea moves.','A little arrow card shows whose turn comes next.'],
['Nori helps Pip count.','Pip thanks his friend.','They are working toward a shared finish, not a race against one another.'],
['All three reach the treehouse.','The game has room for everyone.','Their festival page records how one small invitation changed the afternoon.']]],
['The Library Bus','bus library book seat driver stop',[
['The club waits for a bus.','An adult waits with them.','They stand back from the road at the marked stop.'],
['The bus stops.','The driver opens the door.','The explorers wait for the adult before boarding.'],
['Pip finds a seat.','He holds his book.','Nori sits beside him while the bus starts moving.'],
['The library comes into view.','The adult checks the stop.','They wait until the bus has stopped before standing to leave.'],
['Nori returns a book.','Pip chooses a new story.','The librarian shows them the picture-book shelf.'],
['The club goes home together.','The new book is in a bag.','Their town map connects the bus stop with the library.']]],
['A Helmet for the Journey','helmet bike wheel road park adult',[
['Nori has a bike.','The club plans a park visit.','An adult checks the bike before the trip.'],
['Nori finds her helmet.','The adult checks its fit.','The straps are adjusted before Nori starts riding.'],
['Pip checks a wheel picture.','His picture has a loose part.','He tells the adult rather than trying to repair a real bike alone.'],
['The adult chooses a safe route.','The club stays together.','They follow local crossing rules and the adult’s directions.'],
['Nori reaches the park.','She parks her bike carefully.','Her helmet stays on until she has finished riding.'],
['The friends draw the journey.','They add the helmet first.','The map reminds them that getting ready is part of an adventure.']]],
['Soup for the Story Club','soup pot spoon carrot adult hot',[
['Bea makes a soup plan.','An adult reads it with her.','The club chooses a pretend recipe for its kitchen story.'],
['Pip finds a carrot card.','Nori finds a potato card.','They place the two picture ingredients beside the recipe.'],
['The adult uses the pot.','The pot is hot.','The children stay back from the real stove and sharp tools.'],
['Bea sets out spoons.','Pip brings bowls.','The adult checks portions and food needs before serving.'],
['The soup cools down.','The adult says it is ready.','The friends wait rather than tasting straight from a hot pot.'],
['The club eats together.','Nori tells a short story.','Their kitchen page shows that adults handle heat while children help safely.']]],
['The Basket With Three Clues','basket bread apple cheese market buy',[
['Pip has a shopping list.','The list has three clues.','An adult walks with the club through the market.'],
['The first clue is a loaf.','Pip finds the bread.','He compares the shape with the drawing on the list.'],
['The next clue is red and round.','Nori finds the apple.','The picture also shows a little stem to make the clue clearer.'],
['The last clue is a yellow wedge.','Bea finds the cheese.','The adult checks the package and any food requirements.'],
['The basket has three foods.','The adult pays at the shop.','Pip checks the list again before they leave.'],
['The club returns home.','The shopping clues are solved.','Their market page connects each written word with its picture and food.']]],
['The Box Behind the Clock','box behind clock inside key open',[
['Nori finds a clue.','It says behind the clock.','The clue is part of a pretend treasure game inside the treehouse.'],
['Pip looks beside the clock.','He sees only a book.','Nori points to the word behind and asks him to try another place.'],
['Bea looks behind the clock.','A small box is there.','The clock is a lightweight game prop on a low table.'],
['The box is closed.','Nori finds a paper key.','The key has the same leaf symbol as the box.'],
['Nori opens the box.','A picture is inside.','It shows the friends standing beside the reading tree.'],
['The picture goes in the Atlas.','The clue worked.','Pip draws beside and behind as different places around the clock.']]],
['Left at the Reading Rock','left right between near far map',[
['Pip opens a map.','A star marks the reading rock.','The club is following a pretend trail with an adult.'],
['The first arrow points left.','Nori turns left at the rock.','She keeps the map facing the same way as the path.'],
['Two bushes are ahead.','The path goes between them.','The explorers use the marked path rather than pushing through plants.'],
['A sign is near the bench.','A blue flag is far away.','Bea compares both distances from where she is standing.'],
['The next arrow points right.','The club finds the story box.','Pip checks the final symbol before opening the pretend treasure.'],
['The map is complete.','Nori retells the turns.','Left, between, and right helped the club reach the same destination.']]],
['The Upside-Down Morning','morning breakfast night bedtime before after',[
['Pip has a morning chart.','The pictures are mixed up.','A bedtime picture is at the start of his school-day plan.'],
['Nori finds the breakfast picture.','Breakfast belongs in the morning.','She asks Pip which activity usually comes before leaving home.'],
['Bea finds a bedtime picture.','It belongs near the night picture.','The club is arranging Pip’s routine, not a rule for every family.'],
['Pip puts breakfast first.','He puts school after breakfast.','He checks the order against the routine he follows with his grown-up.'],
['Bedtime goes after dinner.','The chart makes sense now.','Nori adds an arrow to show the way to read the sequence.'],
['Pip starts his morning.','He knows what comes next.','The club keeps blank cards so a different family can make a different routine.']]],
['Tomorrow’s Lantern Walk','today tomorrow evening night early late',[
['Nori wants a lantern walk.','The walk is tomorrow.','Today the club is only getting the little lights ready.'],
['Pip checks the calendar.','He points to today.','Then he moves one square forward to the day marked for the walk.'],
['Bea draws an evening sky.','The walk starts in the evening.','An adult chooses a safe route and a suitable time.'],
['Pip arrives early.','He waits with the adult.','The walk will not begin until the whole group is ready.'],
['The friends meet the next evening.','Their lanterns glow.','They stay together and follow the adult along the checked path.'],
['Nori marks the calendar.','The walk happened today.','The day that was tomorrow during planning is now the day of the adventure.']]],
['The Boat That Would Not Float','boat float sink test change water',[
['Bea makes a tiny boat.','It is a virtual boat on a screen.','The club can test materials without putting anything in a real creek.'],
['The first boat sinks.','Its heavy load goes down.','Pip observes the result instead of calling the experiment a failure.'],
['Nori removes one rock.','The boat is lighter.','They change one part so they can compare the next result.'],
['Bea tests the boat again.','This time it floats.','The remaining load is small enough for this boat to stay at the surface.'],
['Pip draws both tests.','One boat is up and one is down.','His notes describe what happened in this model, not a rule that every light object floats.'],
['The club delivers a tiny flag.','The boat carries it across.','Their invention page records a test, a change, and another test.']]],
['A Bridge for a Tiny Wagon','bridge build test strong smooth rough',[
['Pip has a tiny wagon.','It needs a pretend bridge.','The club builds on a tabletop, not over real water.'],
['Nori tries thin paper.','The paper bends.','The toy wagon stays on the table while the club checks the bridge.'],
['Bea folds the paper.','The folded bridge feels stronger.','They have changed its shape while using the same piece of paper.'],
['Pip tests the wagon.','It crosses the folded bridge.','The club watches carefully to see whether the middle still bends.'],
['Nori adds a smooth road.','The wheels roll across it.','A rough scrap made the little wagon harder to move in their earlier trial.'],
['The bridge gets a flag.','The friends draw their design.','Their notes show the folded shape and the result of the toy test.']]],
['The Song With a Missing Beat','drum bell music rhythm loud quiet',[
['Nori plays a drum.','Pip rings a bell.','The club is practicing a short welcome song for the parade.'],
['Bea taps a rhythm.','It goes tap, tap, rest.','The quiet space is part of the pattern, not a mistake.'],
['Pip rings during the rest.','The pattern sounds different.','He looks at Bea’s cards to find where the quiet space belongs.'],
['Bea points to a blank card.','Everyone waits for one beat.','Nori can follow by tapping gently or moving a hand silently.'],
['The friends try again.','The quiet beat is back.','Their song has room for sound, silence, and different ways to join in.'],
['The welcome song is ready.','They play it together.','Their music page shows two sound marks followed by one empty space.']]],
['The Atlas Comes Alive','parade story picture friend together goodbye',[
['Pip opens the Atlas.','Its pages are full of pictures.','Each region has sent a page made by its explorers.'],
['Bea shows her creek page.','It has a tail and a dam.','She explains that the lodge and dam have different jobs.'],
['Nori shows a friendship page.','It has three game tokens.','She remembers the invitation that made room for another player.'],
['One page is still empty.','It belongs to the new explorer.','The club does not choose the picture for its newest friend.'],
['The explorer chooses a story.','Pip helps add a picture.','A spoken memory, a drawing, or pointing to a favorite page can all tell the club what mattered.'],
['The Story Parade begins.','The friends wave together.','The Atlas is ready for new discoveries whenever the explorer wants to return.']]],
];
