// Aligned to the exact-form seed inventory in the specification. These are contextual glosses,
// not a claim that one translation covers every English sense.
export const glossGroups = [
'你好|朋友|名字|家人|母親|父親|姊妹|兄弟|嬰兒|奶奶／外婆|爺爺／外公|人|小孩|大人|男孩|女孩|鄰居|微笑|擁抱|再見',
'身體|頭|臉|頭髮|眼睛|耳朵|鼻子|嘴巴|牙齒|舌頭|脖子|肩膀|手臂|手|手指|腿|膝蓋|腳|腳趾|皮膚',
'紅色|藍色|黃色|綠色|橘色|紫色|粉紅色|棕色|黑色|白色|灰色|圓形|正方形|三角形|長方形|星形|愛心形|橢圓形|線|點',
'一|二|三|四|五|六|七|八|九|十|十一|十二|十三|十四|十五|十六|十七|十八|十九|二十',
'家|房子|房間|門|窗戶|牆|屋頂|地板|床|枕頭|毯子|椅子|桌子|燈|沙發|架子|時鐘|鏡子|地毯|鑰匙',
'蘋果|香蕉|梨子|桃子|葡萄|檸檬|草莓|藍莓|甜瓜|櫻桃|胡蘿蔔|馬鈴薯|番茄|豌豆|豆子|玉米|麵包|米飯|牛奶|起司',
'貓|狗|兔子|倉鼠|小貓|小狗|寵物|碗|刷子|牽繩|餵食|喝|洗|乾淨的／清潔|睡覺|休息|醒來|溫柔的|柔軟的|小心的',
'河狸|鴨子|青蛙|烏龜|水獺|魚|池塘|河流|溪流|湖泊|水壩|河狸的巢屋|毛皮|尾巴|扁平的|游泳|木材|泥巴|樹枝|河岸',
'狐狸|鹿|熊|松鼠|浣熊|貓頭鷹|森林|樹|葉子|樹枝|樹根|樹皮|種子|堅果|獸穴|樹洞|灌木|苔蘚|足跡|爪子',
'蜜蜂|蝴蝶|螞蟻|甲蟲|瓢蟲|蜘蛛|蚯蚓|蝸牛|昆蟲|翅膀|觸角|花瓣|花|花園|土壤|挖|種植|成長|小的|極小的',
'獅子|大象|長頸鹿|斑馬|猴子|老虎|貓熊|河馬|駱駝|袋鼠|象鼻|長牙|條紋|斑點|長的|短的|高的|重的|輕的|強壯的',
'鯨魚|海豚|鯊魚|海豹|螃蟹|章魚|魷魚|水母|殼|珊瑚|海洋|海灘|沙|海浪|魚鰭|鰭狀肢|觸手|潮汐|深的|淺的',
'乳牛|豬|綿羊|山羊|馬|母雞|小雞|公雞|穀倉|乾草|羊毛|蹄|圍欄|拖拉機|農夫|田地|農作物|小麥|蛋|收成',
'襯衫|長褲|短褲|洋裝|裙子|襪子|鞋子|靴子|帽子|大衣|夾克|毛衣|連指手套|分指手套|圍巾|口袋|鈕扣|拉鍊|皮帶|雨傘',
'太陽|月亮|雲|雨|雪|風|霧|暴風雨|彩虹|天空|熱的|冷的|溫暖的|涼爽的|濕的|乾的|晴朗的|下雨的|下雪的|有風的',
'學校|老師|學生|教室|書桌|書|頁|鉛筆|蠟筆|橡皮擦|紙|剪刀|膠水|背包|課程|故事|字母／信件|單字|問題|答案',
'跑|走|跳|單腳跳|跳步|爬行|攀爬|溜滑梯／滑動|盪鞦韆|丟|接住|踢|滾動|彈跳|跳舞|伸展|球|轉向／輪流|停止|開始',
'快樂的|難過的|生氣的|害怕的|興奮的|平靜的|自豪的|害羞的|友善的|勇敢的|孤單的|疲累的|飢餓的|口渴的|抱歉|請|感謝|分享|幫助|等待',
'城鎮|街道|道路|人行道|行人穿越處|標誌|公車|汽車|卡車|火車|腳踏車|船|飛機|輪子|座位|安全帽|司機|車站|圖書館|公園',
'商店|市場|錢|硬幣|價格|買|賣|袋子|籃子|瓶子|杯子|盤子|湯匙|叉子|鍋子|平底鍋|湯|三明治|餅乾|午餐',
'在上方|在下方|在旁邊|在兩者之間|在後面|近的|遠的|左邊|右邊|頂端|底部|前面|後面|在裡面|在外面|空的|滿的|開著的|關著的|相反的',
'早上|下午|傍晚|夜晚|今天|明天|昨天|一天|一週|月份|年|小時|分鐘|早的|晚的|早餐|晚餐|洗澡|睡覺時間|週末',
'建造|修理|測試|改變|推|拉|浮起|下沉|磁鐵|金屬|塑膠|石頭|玻璃|橡膠|光滑的|粗糙的|堅硬的|圓的|直的|彎曲的',
'音樂|歌曲|鼓|鈴|長笛|鋼琴|吉他|節奏|大聲的|安靜的|快的|慢的|圖片|顏料／畫畫|畫|顏色|形狀|圖案|服裝|遊行',
'一個|一個（母音前）|這個／那個（定冠詞）|這個|那個|我|你|他|她|它|我們|他們|我（受詞）|他（受詞）|她（受詞／所有格）|我們（受詞）|他們（受詞）|我的|你的|他的',
'我們的|他們的|全部|其他的|許多|更多|少量的／小的|不|不是|是的|和|或者|但是|因為|所以|如果|然後|如同／當…時|何時|誰',
'什麼|哪裡|為什麼|如何|是（I用）|是（單數）|是（複數／you）|是（過去單數）|是（過去複數／you）|是（原形）|有|有（第三人稱）|有（過去）|做|做（第三人稱）|做（過去）|能夠|可以（過去／委婉）|將會|會（假設／委婉）',
'到|的|在裡面|在上面|在|在旁邊／藉由|為了|從|和／帶著|沒有|進入|到…上面|出去|向上|向下|在上方／越過|在下面|穿過|周圍|橫過',
'之前|之後|再一次|也|也／太|非常|剛剛／只是|只有|甚至|這裡|那裡|現在|總是|從不|有時候|通常|經常|一起|離開|關於',
'看見|看|聽見|聆聽|說|告訴|問|閱讀|寫|吃|去|來|得到|製作|給|拿|找到|喜歡|想要|需要',
];
export const pictograms = {
 hello:'👋',friend:'🧑‍🤝‍🧑',family:'👨‍👩‍👧',baby:'👶',smile:'😊',goodbye:'👋',head:'🧑',eye:'👁️',ear:'👂',nose:'👃',mouth:'👄',tooth:'🦷',tongue:'👅',hand:'✋',leg:'🦵',foot:'🦶',
 red:'🔴',blue:'🔵',yellow:'🟡',green:'🟢',orange:'🟠',purple:'🟣',brown:'🟤',black:'⚫',white:'⚪',circle:'⚪',square:'🟨',triangle:'🔺',star:'⭐',heart:'💛',
 home:'🏠',house:'🏡',door:'🚪',window:'🪟',bed:'🛏️',chair:'🪑',lamp:'💡',sofa:'🛋️',clock:'🕒',mirror:'🪞',key:'🔑',
 apple:'🍎',banana:'🍌',pear:'🍐',peach:'🍑',grape:'🍇',lemon:'🍋',strawberry:'🍓',blueberry:'🫐',melon:'🍈',cherry:'🍒',carrot:'🥕',potato:'🥔',tomato:'🍅',pea:'🫛',bean:'🫘',corn:'🌽',bread:'🍞',rice:'🍚',milk:'🥛',cheese:'🧀',
 cat:'🐈',dog:'🐕',rabbit:'🐇',hamster:'🐹',kitten:'🐈',puppy:'🐕',bowl:'🥣',brush:'🪥',sleep:'😴',rest:'🛌',
 beaver:'🦫',duck:'🦆',frog:'🐸',turtle:'🐢',otter:'🦦',fish:'🐟',wood:'🪵',stick:'🪵',
 fox:'🦊',deer:'🦌',bear:'🐻',squirrel:'🐿️',raccoon:'🦝',owl:'🦉',forest:'🌲',tree:'🌳',leaf:'🍃',seed:'🌱',nut:'🌰',paw:'🐾',
 bee:'🐝',butterfly:'🦋',ant:'🐜',beetle:'🪲',ladybug:'🐞',spider:'🕷️',worm:'🪱',snail:'🐌',wing:'🪽',flower:'🌼',garden:'🌷',plant:'🌱',
 lion:'🦁',elephant:'🐘',giraffe:'🦒',zebra:'🦓',monkey:'🐒',tiger:'🐅',panda:'🐼',hippo:'🦛',camel:'🐪',kangaroo:'🦘',
 whale:'🐋',dolphin:'🐬',shark:'🦈',seal:'🦭',crab:'🦀',octopus:'🐙',squid:'🦑',jellyfish:'🪼',shell:'🐚',coral:'🪸',ocean:'🌊',beach:'🏖️',wave:'🌊',
 cow:'🐄',pig:'🐖',sheep:'🐑',goat:'🐐',horse:'🐎',hen:'🐔',chick:'🐥',rooster:'🐓',tractor:'🚜',wheat:'🌾',egg:'🥚',
 shirt:'👕',pants:'👖',shorts:'🩳',dress:'👗',sock:'🧦',shoe:'👟',boot:'🥾',hat:'🎩',coat:'🧥',glove:'🧤',scarf:'🧣',umbrella:'☂️',
 sun:'☀️',moon:'🌙',cloud:'☁️',rain:'🌧️',snow:'❄️',wind:'🌬️',fog:'🌫️',storm:'⛈️',rainbow:'🌈',hot:'🥵',cold:'🥶',sunny:'☀️',rainy:'🌧️',snowy:'🌨️',windy:'🌬️',
 school:'🏫',teacher:'🧑‍🏫',student:'🧑‍🎓',book:'📖',page:'📄',pencil:'✏️',crayon:'🖍️',paper:'📃',scissors:'✂️',backpack:'🎒',letter:'✉️',question:'❓',answer:'💬',
 run:'🏃',walk:'🚶',climb:'🧗',dance:'💃',ball:'⚽',stop:'🛑',
 happy:'😊',sad:'😢',angry:'😠',scared:'😨',excited:'🤩',calm:'😌',proud:'😎',shy:'🫣',tired:'🥱',hungry:'🍽️',thirsty:'🥤',help:'🤝',
 town:'🏘️',street:'🛣️',road:'🛣️',bus:'🚌',car:'🚗',truck:'🚚',train:'🚂',bike:'🚲',boat:'⛵',plane:'✈️',wheel:'🛞',helmet:'🪖',station:'🚉',library:'📚',park:'🏞️',
 shop:'🏪',market:'🏬',money:'💵',coin:'🪙',bag:'🛍️',basket:'🧺',bottle:'🍼',cup:'☕',plate:'🍽️',spoon:'🥄',fork:'🍴',pot:'🍲',pan:'🍳',soup:'🥣',sandwich:'🥪',cookie:'🍪',lunch:'🍱',
 left:'⬅️',right:'➡️',up:'⬆️',down:'⬇️',morning:'🌅',evening:'🌇',night:'🌃',breakfast:'🥣',dinner:'🍽️',bath:'🛁',bedtime:'🛌',
 build:'🏗️',fix:'🔧',test:'🧪',magnet:'🧲',rock:'🪨',glass:'🥛',music:'🎵',song:'🎶',drum:'🥁',bell:'🔔',flute:'🪈',piano:'🎹',guitar:'🎸',picture:'🖼️',paint:'🎨',draw:'🖍️',color:'🎨',parade:'🎉',
};
export const coreExamples = [
'I see a cat.|I see an apple.|The cat is here.|This is my bag.|That is your book.|I can help.|You can come.|He has a hat.|She has a book.|It is red.|We can play.|They are here.|Give it to me.|I see him.|I see her.|Come with us.|Look at them.|This is my cup.|That is your cup.|It is his hat.',
'This is our home.|That is their boat.|All the friends can come.|Try the other door.|Many trees grow here.|We need more chairs.|A little rain falls.|No, thank you.|It is not blue.|Yes, please.|Pip and Nori read.|Choose red or blue.|It is small but strong.|We go inside because it rains.|It rains, so we go inside.|If you need help, ask.|First look, then choose.|It is as soft as wool.|When do we go?|Who has the key?',
'What is in the box?|Where is the book?|Why is the paper wet?|How does it move?|I am here.|The tail is flat.|The friends are here.|It was cold.|They were here.|We can be kind.|I have a book.|Pip has a bag.|She had a key.|What do you see?|What does Pip see?|What did you find?|I can swim.|Could you help me?|We will go tomorrow.|I would like a book.',
'Go to the door.|A page of the book.|The key is in the box.|The book is on the table.|Meet at the tree.|Stand by the door.|This is for you.|A letter from Nori.|Read with me.|We can play without a microphone.|Put it into the bag.|The cat jumps onto the bed.|Come out of the room.|Look up.|Sit down.|The bird flies over the tree.|The key is under the book.|Walk through the door.|Look around the room.|The boat goes across the pond.',
'Wash before lunch.|Rest after the game.|Try again.|Nori also has a book.|I want one too.|The water is very cold.|We just arrived.|Only one chair is empty.|Even a tiny snail has a place.|Come here.|The book is there.|We can start now.|Always ask before touching a pet.|Never pull a pet’s tail.|Sometimes we read outside.|We usually meet here.|We often tell stories.|We play together.|The stick floats away.|This story is about a beaver.',
'I see a fish.|Look at the tail.|I hear a bell.|Listen to the story.|Say hello.|Tell me a story.|Ask for help.|Read a book.|Write your name.|We eat lunch.|Go to the treehouse.|Come with me.|Get your bag.|Make a picture.|Give Nori the book.|Take a turn.|Find the key.|I like this story.|I want water.|We need a chair.',
].map(x=>x.split('|')).flat();
// Explicit phoneme/grapheme examples. No guessed consonant speech from letter names.
export const phonics = [
 {id:'cat',word:'cat',parts:['c','a','t'],sounds:['/k/','/æ/','/t/'],pattern:'short-a',rhyme:'hat',distractor:'dog'},
 {id:'hat',word:'hat',parts:['h','a','t'],sounds:['/h/','/æ/','/t/'],pattern:'short-a',rhyme:'cat',distractor:'pig'},
 {id:'pig',word:'pig',parts:['p','i','g'],sounds:['/p/','/ɪ/','/g/'],pattern:'short-i',rhyme:'dig',distractor:'sun'},
 {id:'sun',word:'sun',parts:['s','u','n'],sounds:['/s/','/ʌ/','/n/'],pattern:'short-u',rhyme:'run',distractor:'cat'},
 {id:'dog',word:'dog',parts:['d','o','g'],sounds:['/d/','/ɑ/','/ɡ/'],pattern:'short-o',rhyme:'fog',distractor:'hen'},
 {id:'hen',word:'hen',parts:['h','e','n'],sounds:['/h/','/ɛ/','/n/'],pattern:'short-e',rhyme:'ten',distractor:'coat'},
 {id:'fish',word:'fish',parts:['f','i','sh'],sounds:['/f/','/ɪ/','/ʃ/'],pattern:'digraph-sh',rhyme:null,distractor:'cat'},
 {id:'ship',word:'shop',parts:['sh','o','p'],sounds:['/ʃ/','/ɑ/','/p/'],pattern:'digraph-sh',rhyme:null,distractor:'sun'},
 {id:'coat',word:'coat',parts:['c','oa','t'],sounds:['/k/','/oʊ/','/t/'],pattern:'vowel-team-oa',rhyme:'boat',distractor:'pig'},
];
