import { mkdir, cp, rm } from 'node:fs/promises';
await import('./compile-content.mjs');
await rm('dist', {recursive:true,force:true});
await mkdir('dist', {recursive:true});
for (const path of ['index.html','app.css','src']) await cp(path, `dist/${path}`, {recursive:true});
await mkdir('dist/content');
await cp('content/catalog.json','dist/content/catalog.json');
await mkdir('dist/assets');
for(const name of ['world','beaver','treehouse']) await cp(`assets/${name}.webp`,`dist/assets/${name}.webp`);
console.log('Static build complete. Relative asset paths support /kids_place/ on GitHub Pages.');
